name: app_test
description: App Test

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none"
# Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  google_fonts: ^3.0.1
  cupertino_icons: ^1.0.5
  flutter_dotenv: ^5.0.2
  flutter_modular: ^5.0.3
  mobx: ^2.1.1
  flutter_mobx: ^2.0.6+4
  build_runner: ^2.3.2
  easy_localization: ^3.0.1
  flutter_svg: ^1.1.6
  brasil_fields: ^1.6.0
  dio: ^4.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.1
  mobx_codegen: ^2.0.7+3
  modular_test: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/icons/
    - assets/fonts/
    - assets/fonts/google_fonts/
    - assets/translations/
    - .env.local
    - .env.development
    - .env.production
    - .env.test

  fonts:
    - family: NunitoSans
      fonts:
        - asset: assets/fonts/google_fonts/NunitoSans-Black.ttf
        - asset: assets/fonts/google_fonts/NunitoSans-BlackItalic.ttf
        - asset: assets/fonts/google_fonts/NunitoSans-Bold.ttf
        - asset: assets/fonts/google_fonts/NunitoSans-BoldItalic.ttf
        - asset: assets/fonts/google_fonts/NunitoSans-ExtraBold.ttf
        - asset: assets/fonts/google_fonts/NunitoSans-ExtraBoldItalic.ttf
        - asset: assets/fonts/google_fonts/NunitoSans-ExtraLight.ttf
        - asset: assets/fonts/google_fonts/NunitoSans-ExtraLightItalic.ttf
        - asset: assets/fonts/google_fonts/NunitoSans-Italic.ttf
        - asset: assets/fonts/google_fonts/NunitoSans-Light.ttf
        - asset: assets/fonts/google_fonts/NunitoSans-LightItalic.ttf
        - asset: assets/fonts/google_fonts/NunitoSans-Regular.ttf
        - asset: assets/fonts/google_fonts/NunitoSans-SemiBold.ttf
        - asset: assets/fonts/google_fonts/NunitoSans-SemiBoldItalic.ttf

  uses-material-design: true
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

scripts:
  mobx_build: $clean & $get & $runner build --delete-conflicting-outputs
  mobx_watch: $clean & $get & $runner watch --delete-conflicting-outputs --use-polling-watcher

vars:
  clean: flutter clean
  get: flutter pub get
  runner: flutter pub run build_runner
